final List<String> categories = ['All', 'Sports', 'Food', 'Kids', 'Creative'];
final List<Map<String, dynamic>> activities = [
  // Early Morning
  {
    'title': 'Beach Yoga',
    'time': '08:00 (60 min)',
    'location': 'Playa de la Rada',
    'price': '9€',
    'spots': '0 spot left',
    'intensity': 'Light',
    'available': false,
    'category': 'Early Morning',
    'description': 'Perfect sunrise session',
    'instructor': 'Maria',
    'type': 'Outdoor session',
    'childcare': false,
  },
  {
    'title': 'Beach Yoga Flow',
    'time': '09:00 (60 min)',
    'location': 'Playa de la Rada',
    'price': '9€',
    'spots': '6 spots left',
    'intensity': 'Medium',
    'available': true,
    'category': 'Early Morning',
    'description': 'Coffee meetup after',
    'instructor': 'Maria',
    'type': 'Outdoor session',
    'childcare': false,
  },
  {
    'title': 'Reformer Pilates',
    'time': '09:00 (60 min)',
    'location': 'Wellness Studio',
    'price': '15€',
    'spots': '4 spots left',
    'intensity': 'Medium',
    'available': true,
    'childcare': false,
    'category': 'Early Morning',
    'instructor': 'Ana',
  },
  // Lunch Time Energy
  {
    'title': '5-a-side Football',
    'time': '12:30 (45 min)',
    'location': 'Sports Center',
    'price': '19€',
    'spots': '4 spots left',
    'intensity': 'High',
    'available': true,
    'childcare': true,
    'category': 'Lunch Time Energy',
    'description': 'All levels welcome',
    'instructor': 'Carlos',
  },
  {
    'title': 'Outdoor HYROX',
    'time': '12:30 (45 min)',
    'location': 'Beach Training Area',
    'price': '19€',
    'spots': '6 spots left',
    'intensity': 'Very High',
    'available': false,
    'childcare': true,
    'category': 'Lunch Time Energy',
    'description': 'Functional fitness',
    'instructor': 'James',
    'type': 'Outdoor session',
  },
  {
    'title': '5-a-side Football',
    'time': '13:15 (45 min)',
    'location': 'Sports Center',
    'price': '19€',
    'spots': '3 spots left',
    'intensity': 'High',
    'available': true,
    'childcare': true,
    'category': 'Lunch Time Energy',
    'description': 'Competitive group',
    'instructor': 'Carlos',
  },
  {
    'title': 'MMA Outdoors',
    'time': '13:15 (45 min)',
    'location': 'Beach Training Area',
    'price': '19€',
    'spots': '5 spots left',
    'intensity': 'High',
    'available': true,
    'childcare': true,
    'category': 'Lunch Time Energy',
    'description': 'Beginner friendly',
    'instructor': 'Mike',
    'type': 'Outdoor session',
  },
  // Afternoon & Evening
  {
    'title': 'Kids LEGO Club',
    'time': '15:00 - 20:00',
    'location': 'Creative Center',
    'price': '10€/hour',
    'spots': '8 spots left',
    'intensity': 'Light',
    'available': true,
    'category': 'Afternoon & Evening',
    'description': 'Workspace available • Drop-in available',
    'instructor': 'Sofia',
    'childcare': true,
  },
  {
    'title': '5-a-side Football',
    'time': '16:00 (60 min)',
    'location': 'Sports Center',
    'price': '19€',
    'spots': '6 spots left',
    'intensity': 'High',
    'available': true,
    'childcare': true,
    'category': 'Afternoon & Evening',
    'description': 'After school special',
    'instructor': 'Carlos',
  },
];
